export const FETCH_MARKE='FETCH_MARKE';
export const CREATE_MARKE='CREATE_MARKE';
export const FETCH_MARKU='FETCH_MARKU';
export const UPDATE_MARKE='UPDATE_MARKE';
export const DELETE_MARKE='DELETE_MARKE';

export const FETCH_TIPOVI='FETCH_TIPOVI';
export const CREATE_TIPOVI='CREATE_TIPOVI';
export const FETCH_TIP='FETCH_TIP';
export const UPDATE_TIPOVI='UPDATE_TIPOVI';
export const DELETE_TIPOVI='DELETE_TIPOVI';

export const FETCH_STATUSI='FETCH_STATUSI';
export const CREATE_STATUSI='CREATE_STATUSI';
export const FETCH_STATUS='FETCH_STATUS';
export const UPDATE_STATUSI='UPDATE_STATUSI';
export const DELETE_STATUSI='DELETE_STATUSI';

export const FETCH_VOZILA='FETCH_VOZILA';
export const CREATE_VOZILA='CREATE_VOZILA';
export const FETCH_VOZILO='FETCH_VOZILO';
export const UPDATE_VOZILA='UPDATE_VOZILA';
export const DELETE_VOZILA='DELETE_VOZILA';