export const FETCH_MARKE='FETCH_MARKE';
export const CREATE_MARKE='CREATE_MARKE';
export const FETCH_MARKU='FETCH_MARKU';
export const UPDATE_MARKE='UPDATE_MARKE';
export const DELETE_MARKE='DELETE_MARKE';

export const FETCH_TIPOVI='FETCH_TIPOVI';
export const CREATE_TIPOVI='CREATE_TIPOVI';
export const FETCH_TIP='FETCH_TIP';
export const UPDATE_TIPOVI='UPDATE_TIPOVI';
export const DELETE_TIPOVI='DELETE_TIPOVI';

export const FETCH_STATUSI='FETCH_STATUSI';
export const CREATE_STATUSI='CREATE_STATUSI';
export const FETCH_STATUS='FETCH_STATUS';
export const UPDATE_STATUSI='UPDATE_STATUSI';
export const DELETE_STATUSI='DELETE_STATUSI';

export const FETCH_CINOVI='FETCH_CINOVI';
export const CREATE_CINOVI='CREATE_CINOVI';
export const FETCH_CIN='FETCH_CIN';
export const UPDATE_CINOVI='UPDATE_CINOVI';
export const DELETE_CINOVI='DELETE_CINOVI';

export const FETCH_VOZACI='FETCH_VOZACI';
export const CREATE_VOZACI='CREATE_VOZACI';
export const FETCH_VOZACA='FETCH_VOZACA';
export const UPDATE_VOZACI='UPDATE_VOZACI';
export const DELETE_VOZACI='DELETE_VOZACI';

export const FETCH_VOZILA='FETCH_VOZILA';
export const CREATE_VOZILA='CREATE_VOZILA';
export const FETCH_VOZILO='FETCH_VOZILO';
export const UPDATE_VOZILA='UPDATE_VOZILA';
export const DELETE_VOZILA='DELETE_VOZILA';

export const FETCH_EVIDENCIJE='FETCH_EVIDENCIJE';
export const CREATE_EVIDENCIJE='CREATE_EVIDENCIJE';
export const FETCH_EVIDENCIJA='FETCH_EVIDENCIJA';
export const UPDATE_EVIDENCIJE='UPDATE_EVIDENCIJE';
export const DELETE_EVIDENCIJE='DELETE_EVIDENCIJE';